project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: false

website:
  title: "Girl's Weekend"
  navbar:
    search: true
    pinned: true
    left:
      - href: index.qmd
      - accommodation.qmd
      - text: "Adventures"
        menu: 
          - pottery.qmd
          - swimming.qmd
          - dancing.qmd
          - games.qmd
      - food.qmd
    tools:
      - icon: spotify
        href: https://open.spotify.com/playlist/5uwdCcZvOsJWnbdmml1ydm?si=GIdBRLPHTtacNOJ_QKupag&pi=KYkoE1B-QSuQi
  announcement: 
    icon: chat-heart
    dismissable: true
    content: "**Remember** - Do not hesitate to make suggestions!"
    type: primary
    position: below-navbar

  comments:
    giscus: 
      repo: stringdem95/stringdem95.github.io

format:
  html:
    theme: minty
    css: styles.css