project:
  type: website
  output-dir: docs

website:
  title: "Girl's Getaway Weekend"
  navbar:
    search: true
    pinned: true
    left:
      - href: index.qmd
      - text: "Adventures"
        menu: 
          - pottery.qmd
          - swimming.qmd
          - dancing.qmd
          - games.qmd
      - accommodation.qmd
      - food.qmd

format:
  html:
    theme: minty
    css: styles.css