---
title: "Accommodation"
---
<!-- <details><summary class="collapsible-section"><div class="thePlan h3"><a href="link"></a></div></summary> 
</details> -->


## 5 People Accommodation

<details><summary class="collapsible-section"><div class="thePlan h3"><a href="https://www.airbnb.com.au/rooms/5185777?adults=5&guests=4&search_mode=regular_search&check_in=2026-11-13&check_out=2026-11-15&children=0&infants=0&pets=0&source_impression_id=p3_1783411040_P3_1ExzZVe37fgSE&previous_page_section_name=1000&federated_search_id=c4328101-ed97-4599-8583-39f0469e110c" target="_blank">Entire townhouse in Maroochydore, Australia</a></div></summary> 
<h4>About this space</h4>
BRAND NEW REVERSE AC. Located in the Heart of Cotton Trees only 3 BLKS to Beach+River.TRENDY area with Cool Restaurants,Bakeries,Shops+Bike trails.Good Dogs welcome.Unique rental with EVERYTHING provided-1000 count Sheets,Towels, Unlimited Internet,International+Local calls,BBQ, Beach items, 2 Paddle Boards with wheels to walk them down to river.This 2 bed, 2 bath HM sleeps 6+is set up to feel like a second HM. Designed with great outdoor living,even amazing outdoor surfboard shower.

**The space**  
Good Dogs are allowed with prior approval and a dog deposit. Brand new total renovation designed with all the latest trends and comforts of home - nothing spared. This is a unique rental normally only found overseas - EVERYTHING is provided from the 1000 count sheets, towels, unlimited internet, international  and local calls, and large hooded BBQ, to all the beach items you need! 2 Paddle Boards with wheels to walk them down to the river are available for guest use but you will be required to follow printed directions for cleaning and putting them away as per our book.  
This 2 bedroom, 2 bath home sleeps 6 and is set up to feel like a second home. Designed with great outdoor living, this gorgeous Beach Home boasts a huge wrap around deck with room to seat 12 around the outdoor extension table, with a BBQ provided for your use, large square Umbrella for welcome shade and an amazing outdoor surfboard shower with hot and cold water to wash off the salt water in style.  
Contemporary kitchen is fully equipped with everything a gourmet chef requires - lit appliance cupboard stores every appliance you will need; with a huge Chefs 5 burner free standing oven and cooktop, French-style fridge with ice maker and water dispenser, dishwasher, microwave and a large pantry with the food basics.  An open and bright neutral palette with Australian Spotted gum hardwood floors, Australian contemporary lighting style to feel like a beach home, this open floor plan is great to chill and hang with the family.  
Relax in the comfortable family room with plenty of comfy seating on the  3 person contemporary couch, 2 chairs and 2 ottomans for extras eating, 52” smart TV with DVD for your use. You’ll love the master bedroom with luxury pillow top queen mattress, snuggle into the 1000 count sheets and feather pillows from the USA. You can relax in bed listening to the birds or catch the news on the 40” smart TV, or sip on your morning coffee in the sunshine on your private deck.

Storage is never a problem with lots of closet space with wooden hangers and 6 draw cabinet for extra room. The children’s room is set up with 2 twin beds both with an easy slide out trundle bed; the kids also have luxury pillow top mattresses, 1000 count sheets, quilts and summer blankets.  
Relax and unwind in the stunning upper bathroom in a deep soaking tub with a contemporary 2 sink vanity. In summer we LOVE the Second “bath” which is an outdoor shower, we actually use it more than the tub! The kids love coming home and showering before they go inside! There is an additional toilet on the main level.  A covered carport in front makes it easy to bring in the groceries with a locked storage area for your bikes. Close to everything - surf Maroochydore beach, paddle at the beautiful calm river, and enjoy the wonderful bakery and butcher  just around the corner at Cotton Trees. Shop at the Sunshine Plaza, dine at all the Trendy Restaurants or ride the bike trails all the way to Mooloolabah.  My family has lived here for 50+ years and still have their own units in our complex and I grew up making wonderful beach memories - we hope you do too!  
Only 1 hour from Brisbane and Brisbane airport, 20mins to Australia Zoo, 20mins to Montville and Maleny, 20 mins to Noosa, 10 mins to Sealife Underwater world, 5 mins to Sunshine Plaza. Visit Ettamogah Pub, Aussie World Theme Park, Big Kart Track, Scuba Diving and Deep Sea fishing trips from Mooloolaba, Play Golf, lawn bowls and ten pin bowling at Alex.  
Enjoy this unique experience, unlike any other rental - this was created to feel like a home. Our home. Come share it with us!


You will be able to utilize everything in the home, we only ask if something runs out that you replace it for the next guest.

My family has beach homes in the complex and may be available if you need something.

Maroochydore is, in many ways, the heart of the Sunshine Coast. Maroochydore is best known for its sensational beaches, river precinct, shopping, entertainment and recreational facilities. A long walking track runs from Sunshine Plaza to Cotton Tree and through Alexandra Headland, right up to Mooloolaba, and is always pulsing with people strolling, jogging and cycling along the waterfront.

The kids will spend many happy days at Maroochydore’s perfect beaches. Sunshine Plaza is the Sunshine Coast’s largest shopping mall, and has a large cinema complex, fashion boutiques, department stores and food courts. Maroochydore also offers nightlife with trendy bars and the various Surf Lifesaving Clubs always full of life. When you want to wind down, float on the gentle Maroochydore river current for endless carefree hours, taking time to see the birdlife and coastal eco-system. For things to see and do in Maroochydore, start at the Maroochydore River mouth and try some fishing, stand up paddle boarding or make your way around to the white sands of Maroochydore Beach. Play beach cricket before swimming at the protected beach and grabbing a family meal at the RSL. A few minutes away there’s Top Shots fun park, with mini-golf and watersides.

At Sunshine Plaza there’s the cinema complex with all the latest films, and a shopping mall to satisfy any food or retail desire. Some of Maroochydore’s diverse food and restaurant options include Stillwater for its genuine Japanese dishes, or Ebb for its classy seafood and gourmet meals.

We are located only 1 hour from Brisbane and Brisbane airport, 20mins to Australia Zoo, 20mins to Montville and Maleny, 20 mins to Noosa, 10 mins to Sealife Underwater world, 5 mins to Sunshine Plaza. Visit Ettamogah Pub, Aussie World Theme Park, Big Kart Track, Scuba Diving and Deep Sea fishing trips from Mooloolaba, Play Golf, lawn bowls and ten pin bowling at Alex.

Bring your car or ride your bike! Miles of bike trails along the entire coast!

My Family has owned the land for over 55years and I grew up going to our Beach House every summer walking around to the bakery to get our morning bread and treat! In 1994 we decided to buy an additional lot and develop 'The Paper Barks' so that we could all have our own units. I wanted my kids to experience the simple and fun lifestyle Cotton Trees has to offer so this year we decided to convert my property to a vacation rental. We use is every Christmas and New Year for a month. My Family still owns 4 in the complex that they use regularly.

Guest access
whole house is for rent
</details>

## 4 People Accommodation

<details><summary class="collapsible-section"><div class="thePlan h3"><a href="https://www.airbnb.com.au/rooms/1467943241391902213?adults=4&search_mode=regular_search&check_in=2026-11-06&check_out=2026-11-08&children=0&infants=0&pets=0&source_impression_id=p3_1783154469_P3xBuUvM8wJ10RQr&previous_page_section_name=1000&federated_search_id=016b9dab-0c89-45b2-bbb7-b0c32473b03b" target="_blank">•THE COOLI• Family, pets & beach</a></div></summary>
<h4>About this space</h4>
The Cooli is a family friendly and pet friendly holiday apartment in a small complex of five units. Walk to the Marcoola surf beach (370m), dog friendly beach, parks, restaurants, pubs and cafes.

This is our holiday unit set up with everything we love for the perfect vacation and is yours to enjoy.

Please note, we are located right near the Airport, overhead noise will be present from planes.

15% off for 7+ nights
25% off for 28+ nights
$50 Pet Fee

Check out listings for The Buddi Airbnb.

**The space**  
Located beachside of the Sunshine Coast Airport we have a beautiful fully self-contained kitchen, open living and dining room and full laundry. Two bedrooms with ceiling fans. One bathroom with shower and separate bath, additional standalone toilet room. Both the living room and king bedroom have Smart TVs with complimentary Netflix for the guests to stream. An aircon system with cooling and heating options available lounge room area. A grassed front yard with festoon lighting, table for four and a Webber family BBQ.

Please note we provide a dog bowl for your fur babies, yard is fenced with gate access, please bring bedding as we request no dogs on beds or furniture.

**Guest access**  
Guests will gain access via a self check in process using a coded lock box. Guests will have the whole of apartment 5 to themselves as well as a back yard with BBQ and outdoor seating.

Lock up garage parking provided. Additionally you can park on the street for free.

Access to the apartment has one little step to the door entrance, however it is a single level unit located on ground floor.

**Other things to note**  
A few extras we have included to make your stay as enjoyable as possible;  
- Pod coffee machine with complimentary pods and milk  
- Coffee, tea and sugar  
- Wifi  
- Two smart tvs  
- Netflix complimentary access  
- All bed linen and pillows  
- Bath towels  
- Shampoo, Conditioner and body wash  
- Beach towels  
- Beach Cart  
- Books & Games  
- Dog bowl  
</details>