---
title: "Overview"
---

<details>
  <summary class="collapsible-section"><div class="thePlan h3">What</div></summary>
  <strong>A weekend away.</strong> Leave on Saturday - Have fun - Eventually return home of Sunday.  
  <h4>Current Scheme</h4>
  <strong>Saturday</strong>
  <ul><li>Pottery before lunch.</li>
  <li>Got out for lunch.</li>
  <li>'Check-in' to accomodation.</li>
  <li>Beach afternoon.</li>
  <li>Head back to accommodation and either get ready to go out for dinner or settle in and order food in.</li> 
  <li>Drinks / Games / Dancing</li></ul>
  <strong>Sunday</strong>
  <ul><li>Lazy morning! Sleep in and relax.</li>
  <li>Eventually go out to brunch.</li>
  <li><i>Eventually</i> head home.</li>
  </ul>
</details>
<hr/>
<details>
  <summary class="collapsible-section"><div class="thePlan h3">Where</div></summary>
  <strong>Sunshine Coast.</strong> Close enough that it isn't annoying to get to and get home but far enough that it is a change in environment.
</details>
<hr/>
<details>
  <summary class="collapsible-section"><div class="thePlan h3">When</div></summary>
  <strong>End of October - beginning November.</strong> Hopefully enough time to plan and budget but not too close to the End of year / Christmas chaos.
</details>


# Let's create a weekend playlist 

Sometimes finding the right music can be stressful (well, it is for me) so why not push everyone else into creating a playlist that combines all our music.  
Everyone wins, right?

<a class="btn btn-primary" data-bs-toggle="offcanvas" href="https://open.spotify.com/playlist/5uwdCcZvOsJWnbdmml1ydm?si=GIdBRLPHTtacNOJ_QKupag&pi=KYkoE1B-QSuQi" role="button" aria-controls="offcanvasExample" style="width: stretch;">Add songs to the playlist</a>