---
title: "Pottery"
---

This is a brief overview of some of the classes available at the Sunshine Coast. 

<div class="card border-primary mb-3">
  <div class="card-header"><a href="https://www.syndicatecreative.com.au/">Syndicate Creative</a></div>
  <div class="card-body"><h4 class="card-title" style="margin-top: 0;"><a href="https://www.syndicatecreative.com.au/hand-building-single">Private Hand Building Group Workshop</a></h4>
  <table class="table table-hover">
  <tbody>
    <tr>
      <th scope="row">Duration</th>
      <td>90 minutes</td>
    </tr>
    <tr>
      <th>Cost</th>
      <td>$85.00/person</td>
    </tr>
  </tbody>
</table><p class="card-text">Our Private Hand Building Group Workshops are the perfect workshop for Anniversaries, Birthdays, Work Gatherings or if you just want to learn pottery with your friends! 

Get your hands stuck into some clay and have a laugh while you create! 

Students will be guided to create their own personalised hug mug!

This workshop is perfect for those who want to start small with a single workshop over 90 minutes to create with clay. Your pieces will then be glazed and fired by us and ready for collection around 3 weeks later.

Our Private Group Single sessions include all materials, firings and glazes. 

Are you a beginner? Don’t Fret because our teachers are here to guide you and we want to help you to create something that you can keep forever!</p>
  </div>
</div> 

<div class="card border-primary mb-3">
  <div class="card-header"><a href="https://clayshed.com.au/">The Clay Shed</a></div>
  <div class="card-body"><h4 class="card-title" style="margin-top: 0;"><a href="https://clayshed.com.au/products/pottery-class-make-a-mug">Make a Mug</a></h4>
  <table class="table table-hover">
  <tbody>
    <tr>
      <th scope="row">Duration</th>
      <td>2 hours</td>
    </tr>
    <tr>
      <th>Cost</th>
      <td>$90.00/person</td>
    </tr>
  </tbody>
</table><p class="card-text"><ul><li>Make and decorate your very own mug using easy hand building techniques you can repeat at home! We supply the clay and tools, just bring yourself and some enthusiasm.</li> 
<li>Decorate your mug with our selection of coloured slips and texturing tools.
Plenty of instruction and guidance to ensure you end up with a functional piece you can be proud of.</li>
<li>We will then clear glaze and fire your mug (we will contact you when your mug is ready to be taken home and put to use).</li></ul>
Taught by Stephen Roberts who holds more than 30 years experience as a full time potter, production potter and teacher of pottery.</p>
  </div>
</div>

<div class="card border-primary mb-3">
  <div class="card-header"><a href="https://thepotterystudio.com.au/">The Pottery Studio</a></div>
  <div class="card-body"><h4 class="card-title" style="margin-top: 0;"><a href="https://thepotterystudio.com.au/collections/classes-and-courses/products/clay-wine-class">Clay & Wine Class</a></h4>
  <table class="table table-hover">
  <tbody>
    <tr>
      <th scope="row">Duration</th>
      <td>2 hours</td>
    </tr>
    <tr>
      <th>Cost</th>
      <td>$100.00/person</td>
    </tr>
  </tbody>
</table><p class="card-text">Looking for the perfect way to chill out and get creative? Say hello to Clay & Wine - your new fave way to sip, sculpt, and unwind for 2 beautiful hours of creativity!

Bring your favourite drinks and snacks, pick a project that speaks to you, and get handsy with some clay in a super relaxed, beginner-friendly space. No pressure, no rules - just good vibes, good company, and your own little masterpiece in the making.

👐 Choose your own project  
🎨 Learn hand-building techniques  
🍷 BYO drinks + snacks  
🔥 FREE Glazing Class (INCLUDED): You'll receive a glazing CODE after your making session to use at checkout when booking your glazing class. (Come back in 2 weeks to finish your pieces! Please note you have 2 months to complete your glazing class)

That's 2 classes for the price of 1.
Come play!</p>
  </div>
  <div class="card-body"><h4 class="card-title" style="margin-top: 0;"><a href="https://thepotterystudio.com.au/collections/classes-and-courses/products/wheel-throwing-class">Wheel Throwing Class</a></h4>
  <table class="table table-hover">
  <tbody>
    <tr>
      <th scope="row">Duration</th>
      <td>2 hours</td>
    </tr>
    <tr>
      <th>Cost</th>
      <td>$120.00/person</td>
    </tr>
  </tbody>
</table><p class="card-text">Ready to get your hands dirty and throw some clay around? Join us for a 2 hour crash course in wheel throwing. No experience needed, just a sense of fun.

In this hands-on session, you'll learn how to center clay, shape a cup, and throw a bowl (or something bowl-ish - no pressure!). Our friendly facilitators will guide you every step of the way, then hand over the wheel so you can give it a whirl.

🍷 BYO drinks + snacks  
🎨 Expect to get messy - in the best way  
✨ FREE Glazing Class (INCLUDED): You'll receive a glazing CODE after your making session to use at checkout when booking your glazing class. (Come back in 2 weeks to finish your pieces! Please note you have 2 months to complete your glazing class)

Yep, that's two classes for the price of one.
Let's spin.</p>
  </div>
</div>